### ISSUE TITLE
[GT++] Industrial mixing machines seems not working properly

### ISSUE THREAD

**Issue by 5lx** [GTNewHorizons/NewHorizons#5373]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Tried to mix Ir3Os and Pyrotheum from Industrial mixing machine
#
#### What happened instead? (Attach screenshots if needed)
Machine not working, whereas GT machine works well.
![image](https://user-images.githubusercontent.com/6583339/72660195-3b7e8a80-397f-11ea-8587-2e40a6d2c107.png)

![image](https://user-images.githubusercontent.com/6583339/72660210-a29c3f00-397f-11ea-8cce-2b080f622528.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by 5lx** [comment]
I tried to downgrade the GT++ from 471 to 394, and then the mixer works well again.

**Comment by draknyte1** [comment]
Already fixed in https://github.com/alkcorp/GTplusplus/commit/4f20943f825120db459b9c6547ab2e6c09c0807a.

**Comment by Dream-Master** [comment]
471 is the lastest version why it not worked if it is fixed @draknyte1

**Comment by draknyte1** [comment]
Probably has empty input busses.

**Comment by barsikus007** [comment]
@draknyte1 still not working
![image](https://user-images.githubusercontent.com/37113583/72706848-11d88580-3b70-11ea-86a7-216662720e51.png)
